apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-config-server
  labels:
    app.kubernetes.io/name: app-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-config-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-config-server
    spec:
      containers:
        - name: app-config-server
          image: nginx:1.16.0-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          volumeMounts:  
          - name: datadir
            mountPath: /usr/share/nginx/html
      initContainers:
      - name: init-git
        image: alpine/git:1.0.7
        command: ['git', 'clone', 'https://github.com/rubenvillar/angular-one-build-multiple-environments.git', '/config-dir']
        volumeMounts:
        - name: datadir
          mountPath: /config-dir
      volumes:
      - name: datadir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: app-config-server
  labels:
    app.kubernetes.io/name: app-config-server
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: app-config-server